import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "#F2BAC9",
          light: "#F5DCE5",
          dark: "#E8A4B8",
          foreground: "#5f2a3e",
        },
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-in-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#F2BAC9",
          "primary-content": "#5f2a3e",
          secondary: "#F5DCE5",
          "secondary-content": "#8B5A6B",
          accent: "#E8A4B8",
          neutral: "#3D4451",
          "base-100": "#ffffff",
          "base-200": "#f8fafc",
          "base-300": "#e2e8f0",
          info: "#3abff8",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#f87272",
        },
        dark: {
          primary: "#F2BAC9",
          "primary-content": "#5f2a3e",
          secondary: "#E8A4B8",
          "secondary-content": "#F2BAC9",
          accent: "#D491A8",
          neutral: "#A9B1C3",
          "base-100": "#1f2937",
          "base-200": "#111827",
          "base-300": "#374151",
          info: "#3abff8",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#f87272",
        },
        cupcake: {
          primary: "#F2BAC9",
          "primary-content": "#5f2a3e",
          secondary: "#D4A5A5",
          "secondary-content": "#8B5A6B",
          accent: "#E8D5D5",
          neutral: "#6B5B5B",
          "base-100": "#FFF9F9",
          "base-200": "#FDF3F3",
          "base-300": "#F5E6E6",
          info: "#3abff8",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#f87272",
        },
        bumblebee: {
          primary: "#F2BAC9",
          "primary-content": "#5f2a3e",
          secondary: "#F4D03F",
          "secondary-content": "#7D6608",
          accent: "#2C3E50",
          neutral: "#4B5563",
          "base-100": "#ffffff",
          "base-200": "#f9fafb",
          "base-300": "#f3f4f6",
          info: "#3abff8",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#f87272",
        },
        synthwave: {
          primary: "#F2BAC9",
          "primary-content": "#5f2a3e",
          secondary: "#FF6B9D",
          "secondary-content": "#C41E5A",
          accent: "#00D4FF",
          neutral: "#A0A0A0",
          "base-100": "#2D1B69",
          "base-200": "#1E1042",
          "base-300": "#4C1D95",
          info: "#00D4FF",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#FF6B9D",
        },
        dracula: {
          primary: "#F2BAC9",
          "primary-content": "#5f2a3e",
          secondary: "#C678DD",
          "secondary-content": "#A355C7",
          accent: "#61AFEF",
          neutral: "#ABB2BF",
          "base-100": "#282C34",
          "base-200": "#21252B",
          "base-300": "#181A1F",
          info: "#61AFEF",
          success: "#98C379",
          warning: "#E5C07B",
          error: "#E06C75",
        },
      },
    ],
  },
};
export default config;
